-------------------------------------------------------------------------------
Test set: io.apicurio.tests.auth.SimpleAuthIT
-------------------------------------------------------------------------------
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.13 s <<< FAILURE! -- in io.apicurio.tests.auth.SimpleAuthIT
io.apicurio.tests.auth.SimpleAuthIT.testDevRole -- Time elapsed: 1.269 s <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:437)
	at io.kiota.http.vertx.VertXRequestAdapter.send(VertXRequestAdapter.java:167)
	at io.apicurio.registry.rest.client.users.me.MeRequestBuilder.get(MeRequestBuilder.java:58)
	at io.apicurio.registry.rest.client.users.me.MeRequestBuilder.get(MeRequestBuilder.java:45)
	at io.apicurio.tests.auth.SimpleAuthIT.testDevRole(SimpleAuthIT.java:151)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:431)
	... 7 more
Caused by: io.vertx.core.http.HttpClosedException: Connection was closed

